### ISSUE TITLE
Issue with Plugin Installation on Moodle Version 4.3+ (Build: 20231020) - Loop and Coding Error Detected

### ISSUE THREAD

**Issue by esteban-campos** [EsdrasCaleb/moodle-tool_deletemessage#2]
Dear EsdrasCaleb
,I am writing to report an issue encountered after installing your plugin on Moodle Version 4.3+ (Build: 20231020). After the installation, the platform entered a loop state, continuously displaying the version information screen and system check, followed by a persistent loop.

The specific error message displayed is: "Detected coding error, it must be fixed by a programmer: Unknown plugin type: core."

Actions taken:

Cleared Moodle's cache.
Removed temporary files.
Verified file permissions and directory integrity.
Despite these efforts, the problem persists. The loop prevents access to the Moodle site's administrative functions, significantly affecting usability.

Could you please provide guidance or a fix for this issue? Any insights or instructions you could offer would be greatly appreciated. If additional information or logs are needed, please let me know, and I will provide them promptly.

Thank you for your attention to this matter. I look forward to your response and a possible solution.

Best regards,
Esteban Campos
esteban.campos@puntolab.cl
[.lab]

![1](https://github.com/EsdrasCaleb/moodle-tool_deletemessage/assets/16508698/4485bddc-48e5-47d2-ac24-ef938d2fbcab)
![2](https://github.com/EsdrasCaleb/moodle-tool_deletemessage/assets/16508698/abd65342-a4de-49c2-a6f8-2323280991cf)
![3](https://github.com/EsdrasCaleb/moodle-tool_deletemessage/assets/16508698/6bce8bac-e0cc-476e-858b-3360ba8760f7)

**Comment by EsdrasCaleb** [comment]
Hi I updated my moodle to version 4.3+ and got no errors. I am updating this plugin just now I don´t know if you get this error from a version download here while I was updating.
Can you provide me where you put my plugin. And try to put and _ before its name (eg. _deletemessages) to see if moodle updates without it?

**Comment by EsdrasCaleb** [comment]
@esteban-campos could you please provide this infos or I will cose the issue as I cant reproduce it.
My plugin is a tool plugin not a core one...

**Comment by esteban-campos** [comment]
Dear EsdrasCaleb

I hope this message finds you well. I am writing to provide feedback on the "deletemessage" for Moodle, specifically regarding an installation loop issue we encountered and the effective solution we discovered.

We observed that Moodle was entering an installation loop when attempting to integrate the plugin. After thorough investigation and consideration, we implemented a change in the naming convention of the plugin, specifically within the Moodle > admin > tools directory.

By prefixing the plugin's name with an underscore, transforming it to "_deletemessages," we successfully resolved the installation loop issue. This modification allowed Moodle to recognize and process the plugin without entering the repetitive loop, thus facilitating a smooth and efficient installation process.

I wanted to share this resolution with you, as it may be beneficial for your documentation or future development iterations. This simple yet impactful change could potentially assist other users who might encounter similar issues.

Thank you for your dedication to enhancing the Moodle user experience with your plugin. Please do not hesitate to reach out if you require further details regarding this matter or if there's any other way I can assist.

Best Regards,
Esteban
![4](https://github.com/EsdrasCaleb/moodle-tool_deletemessage/assets/16508698/97f184c4-1261-4bee-ba95-2ea3abe7493a)

**Comment by EsdrasCaleb** [comment]
I asked you to do this. You are puting my pluign in the wrong folder.
You are puting it in  /admin and the correct folder is /admin/tool

**Comment by esteban-campos** [comment]
sorry the plug in was in folder is /admin/tool...

**Comment by esteban-campos** [comment]
The plugin was installed with the moodle site system, not manual installation.

**Comment by EsdrasCaleb** [comment]
Okay The image apears to show in admin folder
The _ before name will make moodle skip the plugin, this is why I asked you to do it. Could you update the plugin code and remove the _ or install it by the moodle interface and see if the problem persists?

**Comment by EsdrasCaleb** [comment]
Could you please install the updated code version and see if it works. 
Sorry for the trumble I guess you got a instable version from this repository. 
I always recomend install from the version inside moodle plugns page.

**Comment by EsdrasCaleb** [comment]
![image](https://github.com/EsdrasCaleb/moodle-tool_deletemessage/assets/1126400/8a7db0ce-5ae7-4b8b-a7f4-6e3720bef9a4)
I still cant reproduce the error here

**Comment by EsdrasCaleb** [comment]
no info provided can't reproduce, can't solve
