### ISSUE TITLE
Task Error Duplicate value

### ISSUE THREAD

**Issue by eledia** [EsdrasCaleb/moodle-tool_deletemessage#4]
We have task error beacause of duplicate value
Please make SELECT DISTINCT in SQL  
/admin/tool/deletemessage/classes/task/delete.php
$sql = "SELECT DISTINCT  m.id as messageid,

++ Did you remember to make the first column something unique in your call to get_records? Duplicate value \'259373\' found in column \'messageid\'. ++
* line 1407 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
*** line 103 of /admin/tool/deletemessage/classes/task/delete.php: call to mysqli_native_moodle_database->get_records_sql()**
* line 410 of /lib/classes/cron.php: call to tool_deletemessage\\task\\delete->execute()
* line 208 of /lib/classes/cron.php: call to core\\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\\cron::run_main_process()

**Comment by EsdrasCaleb** [comment]
HI thx for your report, I add this check and also add a check if the message id exists before the call of \core_message\api::delete_message
